server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://172.16.130.11:3309/cloud_order?useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: orderservice
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos服务地址
      discovery:
        ephemeral: false #是否临时实例
#      discovery:
#        group: MY_GROUP
#      discovery:
#        cluster-name:

mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
#eureka:
#  client:
#    service-url:  # eureka的地址信息
#      defaultZone: http://127.0.0.1:10086/eureka

#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 6000


#springcloud loadbalancer将取代ribbon作为负载均衡组件
#全局ribbon配置
ribbon:
  NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule  # 优先访问同组下同集群的服务
  restclient:
    #RibbonClientHttpRequestFactory
    enabled: true
  #单位ms,请求连接的超时时间，默认1000
  ConnectTimeout: 1000
  #单位ms,读取数据的超时时间，默认1000
  ReadTimeout: 1500
  #对所有操作请求都进行重试
  #设置为true时，会对所有的请求进行重试，若为false只会对get请求进行重试
  #如果是put或post等写操作，
  #如果服务器接口没做幂等性，会产生不好的结果，所以OkToRetryOnAllOperations慎用。
  #默认情况下,GET方式请求无论是连接异常还是读取异常,都会进行重试
  #非GET方式请求,只有连接异常时,才会进行重试
  OkToRetryOnAllOperations: false
  #切换实例的重试次数，默认为1
  MaxAutoRetriesNextServer: 1
  #如果不配置ribbon的重试次数
  #对当前实例的重试次数,默认为0
  MaxAutoRetries: 1
  eager-load:
    enabled: true # 开启饥饿加载
    clients: # 指定饥饿加载的服务名称
      - userservice

#特定服务ribbon配置
#userservice:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule  # 优先访问同组下同集群的服务
#    ReadTimeout: 1000
#    ConnectTimeout: 500
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule

# 配置了feign, ribbon的超时、重试等配置无效
feign:
  httpclient:
    enabled: true # 支持HttpClient的开关
    max-connections: 200 # 最大连接数
    max-connections-per-route: 50 # 单个路径的最大连接数
    connection-timer-repeat: 3000 # 定时检测连接存活情况任的调度频率
  #配置优于代码
  client:
    config:
      default:
        loggerLevel: FULL
        connectTimeout: 200
        readTimeout: 1000
      userservice:
#        loggerLevel: BASIC
        retryer: cn.itcast.order.config.feign.OnceRetryer
#  sentinel:
#    enabled: true